// <auto-generated />
using System;
using GestionnaireFootball.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionnaireFootball.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GestionnaireFootball.Models.Composition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Formation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Compositions", (string)null);
                });

            modelBuilder.Entity("GestionnaireFootball.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adversaire")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ButsContre")
                        .HasColumnType("int");

                    b.Property<int?>("ButsPour")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("EstDomicile")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Score")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DateHeure")
                        .IsUnique();

                    b.ToTable("Matchs", (string)null);
                });

            modelBuilder.Entity("GestionnaireFootball.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DestinataireId")
                        .HasColumnType("int");

                    b.Property<bool>("EstLue")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("JoueurId")
                        .HasColumnType("int");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DestinataireId");

                    b.HasIndex("JoueurId");

                    b.HasIndex("MatchId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("GestionnaireFootball.Models.PosteTerrain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompositionId")
                        .HasColumnType("int");

                    b.Property<int?>("JoueurId")
                        .HasColumnType("int");

                    b.Property<string>("NomPoste")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Ordre")
                        .HasColumnType("int");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompositionId");

                    b.HasIndex("JoueurId");

                    b.ToTable("PostesTerrain", (string)null);
                });

            modelBuilder.Entity("GestionnaireFootball.Models.Presence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateSaisie")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EntrainementId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HeureArrivee")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("JoueurId")
                        .HasColumnType("int");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JoueurId");

                    b.HasIndex("MatchId");

                    b.ToTable("Presences", (string)null);
                });

            modelBuilder.Entity("GestionnaireFootball.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext");

                    b.Property<string>("TypeUtilisateur")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs", (string)null);

                    b.HasDiscriminator<string>("TypeUtilisateur").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GestionnaireFootball.Models.Joueur", b =>
                {
                    b.HasBaseType("GestionnaireFootball.Models.Utilisateur");

                    b.Property<float>("NoteGlobale")
                        .HasColumnType("float");

                    b.Property<int?>("NumeroMaillot")
                        .HasColumnType("int");

                    b.Property<int>("Poste")
                        .HasColumnType("int");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator().HasValue("Joueur");
                });

            modelBuilder.Entity("GestionnaireFootball.Models.Personnel", b =>
                {
                    b.HasBaseType("GestionnaireFootball.Models.Utilisateur");

                    b.Property<DateTime?>("DateEmbauche")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Fonction")
                        .HasColumnType("int");

                    b.Property<string>("Specialite")
                        .HasColumnType("longtext");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator().HasValue("Personnel");
                });

            modelBuilder.Entity("GestionnaireFootball.Models.Composition", b =>
                {
                    b.HasOne("GestionnaireFootball.Models.Match", "Match")
                        .WithMany("Compositions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Match");
                });

            modelBuilder.Entity("GestionnaireFootball.Models.Notification", b =>
                {
                    b.HasOne("GestionnaireFootball.Models.Utilisateur", "Destinataire")
                        .WithMany()
                        .HasForeignKey("DestinataireId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GestionnaireFootball.Models.Joueur", null)
                        .WithMany("Notifications")
                        .HasForeignKey("JoueurId");

                    b.HasOne("GestionnaireFootball.Models.Match", "Match")
                        .WithMany("Notifications")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Destinataire");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("GestionnaireFootball.Models.PosteTerrain", b =>
                {
                    b.HasOne("GestionnaireFootball.Models.Composition", "Composition")
                        .WithMany("PostesTerrain")
                        .HasForeignKey("CompositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionnaireFootball.Models.Joueur", "Joueur")
                        .WithMany("PostesOccupes")
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Composition");

                    b.Navigation("Joueur");
                });

            modelBuilder.Entity("GestionnaireFootball.Models.Presence", b =>
                {
                    b.HasOne("GestionnaireFootball.Models.Joueur", "Joueur")
                        .WithMany("Presences")
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionnaireFootball.Models.Match", "Match")
                        .WithMany("Presences")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Joueur");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("GestionnaireFootball.Models.Composition", b =>
                {
                    b.Navigation("PostesTerrain");
                });

            modelBuilder.Entity("GestionnaireFootball.Models.Match", b =>
                {
                    b.Navigation("Compositions");

                    b.Navigation("Notifications");

                    b.Navigation("Presences");
                });

            modelBuilder.Entity("GestionnaireFootball.Models.Joueur", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("PostesOccupes");

                    b.Navigation("Presences");
                });
#pragma warning restore 612, 618
        }
    }
}
